### ISSUE TITLE
Egret框架入门第一步 - 影片剪辑  这一部分里面的方法感觉已近过期了

### ISSUE THREAD

**Issue by MichaelGong** [NeoGuo/html5-documents#3]
Egret框架入门第一步 - 影片剪辑  这一部分里面的方法感觉已近过期了，能否更新一下代码呢？免得很多像我这种小白都运行不出来 ，然后百度半天才发现，是框架机制更改了额

**Comment by NeoGuo** [comment]
抱歉没有时间及时跟进官方的修改。请以官方文档中心为准。我会在这里加上提醒。
