### ISSUE TITLE
创建使用位图字体的文本对象  中的错误

### ISSUE THREAD

**Issue by MichaelGong** [NeoGuo/html5-documents#4]
在当前版本中的代码应该是：
var bitmapFont = new egret.BitmapText();
bitmapFont.font = RES.getRes('bitmapfont');
bitmapFont.text = "Hello World!";
this.addChild(bitmapFont);
是bitmapFont.font 而不是bitmapFont.spriteSheet

**Comment by NeoGuo** [comment]
抱歉没有时间及时跟进官方的修改。请以官方文档中心为准。
