### ISSUE TITLE
egret找不到DefaultMovieClipDelegate这个方法或属性

### ISSUE THREAD

**Issue by lisaRao** [NeoGuo/html5-documents#9]
`var monkey = new egret.MovieClip(new egret.DefaultMovieClipDelegate(data,texture));`
egret 没有`DefaultMovieClipDelegate` 这个方法

**Comment by NeoGuo** [comment]
抱歉请参考最新版本的Egret官方教程。这个教程是很久以前写的，现在很多API都发生了翻天覆地的变化。
